version: '3'
services:

  # docker load -i docker/homestead.tgz

  #Homestead 
  webserver:
    image: homestead:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
        - ./workspace-www:/var/www
        - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - db
    links:
      - db
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
        - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


volumes:
  db-data:
#     driver: local
#     driver_opts:
#       type: bind
#       device: ../
